# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb9b4741d1c1edca1caf58c5e2741a93e1f2bff26f8389238b386d6bbee1e66a9a9c3addf9ae54a00faca15a6dd95d43658e5edd8f9f0d51e330c322593855c7

test:
  secret_key_base: 9c5c016132a670add1b236bdae84d400b26c2f67a782f845f922e5125fb5251097b4850ecba35edb24c14b3123dbce0bda84f220fc116b690615bea0f9b2e498

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
